### ISSUE TITLE
RTL8188eus not being identified ArchLinux 6.2.7 kernel

### ISSUE THREAD

**Issue by Masrkai** [kimocoder/realtek_wifi#37]
``[ahmed@archy ~]$ lsusb
Bus 001 Device 002: ID 8087:8001 Intel Corp. Integrated Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 0424:5534 Microchip Technology, Inc. (formerly SMSC) Hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 004: ID 8087:0a2a Intel Corp. Bluetooth wireless interface
Bus 002 Device 006: ID 2357:010c TP-Link TL-WN722N v2/v3 [Realtek RTL8188EUS]
Bus 002 Device 003: ID 0424:2134 Microchip Technology, Inc. (formerly SMSC) Hub
Bus 002 Device 002: ID 148f:5370 Ralink Technology, Corp. RT5370 Wireless Adapter
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
``
Although USB says its connected.. iwconfig Doesn't show a wlan2 exists

``lo        no wireless extensions.

enp0s25   no wireless extensions.

wlan0     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=-2147483648 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:on
          
wlan1     IEEE 802.11  ESSID:"====="  
          Mode:Managed  Frequency:2.462 GHz  Access Point:@@@@@@@@ 
          Bit Rate=1 Mb/s   Tx-Power=20 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=47/70  Signal level=-63 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:13  Invalid misc:139   Missed beacon:0

virbr0    no wireless extensions.``

I am kinda new to Linux so easy on me @_@
I was not sure about how i should install this driver I did `make` and then `sudo make install`
And i did blacklist the old driver wich you have mentioned so far like the .ko and r8188eu
![image](https://user-images.githubusercontent.com/118424417/226241601-b133a76b-b29f-4bb4-ba43-b21d19944df8.png)

**Comment by dubhater** [comment]
You probably need to load the module manually:
```
modprobe mac80211
insmod /path/to/your/rtl8xxxu.ko
```

**Comment by Masrkai** [comment]
> insmod /path/to/your/rtl8xxxu.ko

i didnt quite undersand the comand.. well 
after 
sudo make clean
sudo make
sudo make install i still dont have a single .ko file in my directory.. umm 😅

**Comment by ZerBea** [comment]
The driver will be here:
/lib/modules/6.2.7-arch1-1/kernel/drivers/net/wireless/realtek/
where "6.2.7-arch1-1" is the actual installed kernel version, e.g.:

$ uname -r
6.2.7-arch1-1

BTW:
Running Arch Linux it is not a good idea to install the driver via "sudo make install".
On next kernel update Arch Linux detect that you installed something by hand and pacman will not remove the entire old kernel directory.
And, after a kernel update e.g. to 6.2.8 the installed driver will not work any longer.
It is important that you remove this driver before Arch Linux develop kernel 6.3 in a few weeks.
The driver included in kernel 6.3 will work out of the box on RTL8188EU(S), 8192, ...
Also you should notice that Arch Linux prefer (not mandatory) zst compressed modules. 

This is my /etc/modprobe.d/realtik.conf:
blacklist rtl8192cu
blacklist r8188eu

Right now, I'm running this driver:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/net/wireless/realtek/rtl8xxxu?h=v6.3-rc3
because the driver from Christian crashed since I'm on kernel 6.2
https://github.com/kimocoder/realtek_rtwifi/issues/36

**Comment by ZerBea** [comment]
BTW:
`I am kinda new to Linux so easy on me`
You successfully installed Arch Linux. Congratulations - that is more than beginner level!

**Comment by Masrkai** [comment]
Wait.. @ZerBea 
You mean this driver will be a default in Arch 6.3 kernel ????
Or just ahm..the old default driver will just override/overwrite the driver I installed 😅
"Btw your information was very helpful for some other things I needed to do thanks a bunch 💙"

**Comment by ZerBea** [comment]
Correct, the driver will be in Kernel 6.3.
Your installed driver will be ignored after a kernel update.

If you do a pacaman -Syu, the old kernel modules will be removed. Take a look at:
/lib/modules/
and you see the new kernel modules, e.g.
6.2.7-arch1-1
If you have had installed a module outside of pacman. the old folder, e.g. 
6.2.7-arch1-1
will not be removed and you see 2 entries:
6.2.7-arch1-1
6.2.8-arch1-1

You have to rm the old one. Before you do this, make sure that you are on the latest kernel:
$ uname -r
6.2.8-arch1-1

**Comment by Masrkai** [comment]
@ZerBea thanks alot <3
